export enum ReturnReason {
  NO_REASON_GIVEN = 'NO_REASON_GIVEN',
  WRONG_PRODUCT_SHIPPED = 'WRONG_PRODUCT_SHIPPED',
  PRODUCT_ARRIVED_DAMAGED = 'PRODUCT_ARRIVED_DAMAGED',
  CUSTOMER_CHANGED_THEIR_MIND = 'CUSTOMER_CHANGED_THEIR_MIND',
  ARRIVED_TOO_LATE = 'ARRIVED_TOO_LATE',
  DID_NOT_MEET_EXPECTATIONS = 'DID_NOT_MEET_EXPECTATIONS',
  NOT_AS_DESCRIBED = 'NOT_AS_DESCRIBED',
}
