export enum ReturnReason {
	WRONG_ITEM_RECEIVED = "WRONG_ITEM_RECEIVED",
	DEFECTIVE_OR_BROKEN = "DEFECTIVE_OR_BROKEN",
	NOT_AS_DESCRIBED = "NOT_AS_DESCRIBED",
	USER_CHANGED_MIND = "USER_CHANGED_MIND",
	ORDERED_BY_MISTAKE = "ORDERED_BY_MISTAKE",
	FOUND_BETTER_ALTERNATIVE = "FOUND_BETTER_ALTERNATIVE",
	NO_REASON_PROVIDED = "NO_REASON_PROVIDED",
}
